"""Knot-type-specific guided generation.

Test if we can control WHICH knot type is generated by modifying the scoring function
to reward a specific topology (e.g., 3_1, 4_1, 5_1).
"""

import json
import time
from pathlib import Path

import modal

app = modal.App("esm3-typed-gen")

volume = modal.Volume.from_name("esm3-models", create_if_missing=True)
VOLUME_PATH = Path("/vol")
MODELS_PATH = VOLUME_PATH / "models"

esm3_image = (
    modal.Image.debian_slim(python_version="3.12")
    .apt_install("git")
    .pip_install("esm==3.2.3", "torch==2.5.1", "topoly", "huggingface-hub")
    .env({"HF_HOME": str(MODELS_PATH), "TOKENIZERS_PARALLELISM": "false"})
)

MINUTES = 60


@app.function(
    image=esm3_image, volumes={VOLUME_PATH: volume},
    secrets=[modal.Secret.from_name("huggingface-secret")],
    gpu="A10G", timeout=20 * MINUTES,
)
def generate_typed(attempt_id: int, target_type: str, protein_length: int) -> dict:
    """Generate a protein targeting a specific knot type."""
    import os, tempfile, warnings
    warnings.filterwarnings("ignore", category=UserWarning)
    from huggingface_hub import login
    login(token=os.environ["HF_TOKEN"])

    import torch
    from esm.models.esm3 import ESM3
    from esm.sdk.api import ESMProtein
    from esm.sdk.experimental import ESM3GuidedDecoding, GuidedDecodingScoringFunction
    from topoly import alexander

    model = ESM3.from_pretrained("esm3_sm_open_v1").to("cuda")
    model = model.half()
    torch.backends.cuda.matmul.allow_tf32 = True

    def get_topology(protein):
        with tempfile.NamedTemporaryFile(suffix=".pdb", delete=False) as f:
            protein.to_pdb(f.name)
            topo = alexander(f.name, tries=30)
        return topo

    class TypedKnotSF(GuidedDecodingScoringFunction):
        def __call__(self, protein):
            assert protein.ptm is not None
            topo = get_topology(protein)
            total = sum(topo.values())
            if total == 0:
                return 0.0
            target_prob = topo.get(target_type, 0) / total
            any_knot_prob = 1.0 - topo.get("0_1", 0) / total
            # Reward: high weight for target type + some weight for any knot
            return float(target_prob * 2.0 + any_knot_prob * 0.5)

    guided = ESM3GuidedDecoding(client=model, scoring_function=TypedKnotSF())

    t0 = time.time()
    try:
        generated = guided.guided_generate(
            protein=ESMProtein(sequence="_" * protein_length),
            num_decoding_steps=protein_length // 32,
            num_samples_per_step=10, verbose=False)
        topo = get_topology(generated)
        total = sum(topo.values())
        target_prob = topo.get(target_type, 0) / total if total > 0 else 0
        any_knot = 1.0 - topo.get("0_1", 0) / total if total > 0 else 0
        # Clean topo for JSON
        topo_clean = {k: round(v, 4) for k, v in topo.items()}
        dominant_type = max(topo, key=topo.get) if topo else "0_1"

        return {
            "attempt": attempt_id, "target_type": target_type,
            "length": protein_length,
            "target_prob": round(target_prob, 4),
            "any_knot_prob": round(any_knot, 4),
            "topology": topo_clean,
            "dominant_type": dominant_type,
            "hit_target": target_prob > 0.3,
            "time_s": round(time.time() - t0, 1),
            "error": None,
        }
    except Exception as e:
        return {"attempt": attempt_id, "target_type": target_type,
                "error": str(e), "time_s": round(time.time() - t0, 1)}


@app.local_entrypoint()
def main(n_per_type: int = 10, protein_length: int = 300):
    target_types = ["3_1", "4_1", "5_1", "5_2"]
    total = len(target_types) * n_per_type
    print(f"Typed generation: {len(target_types)} types x {n_per_type} = {total}, len={protein_length}")

    all_ids, all_types, all_lens = [], [], []
    for tt in target_types:
        for i in range(n_per_type):
            all_ids.append(hash((tt, i)) & 0xFFFF)
            all_types.append(tt)
            all_lens.append(protein_length)

    t0 = time.time()
    results = list(generate_typed.map(all_ids, all_types, all_lens, return_exceptions=True))
    wall_time = time.time() - t0

    clean = [r if not isinstance(r, Exception) else
             {"attempt": all_ids[i], "target_type": all_types[i], "error": str(r)}
             for i, r in enumerate(results)]

    print(f"\n{'='*60}")
    print(f"TYPED GENERATION ({wall_time/60:.1f} min)")
    print(f"{'='*60}")

    import numpy as np
    for tt in target_types:
        batch = [r for r in clean if r.get("target_type") == tt and r.get("error") is None]
        n_hit = sum(1 for r in batch if r.get("hit_target"))
        n_knotted = sum(1 for r in batch if r.get("any_knot_prob", 0) > 0.5)
        target_probs = [r.get("target_prob", 0) for r in batch]
        dominant_types = [r.get("dominant_type", "?") for r in batch]
        from collections import Counter
        dom_counts = Counter(dominant_types)
        print(f"\nTarget: {tt}")
        print(f"  Knotted: {n_knotted}/{len(batch)}, Hit target: {n_hit}/{len(batch)}")
        print(f"  Mean target prob: {np.mean(target_probs):.3f}")
        print(f"  Dominant types: {dict(dom_counts)}")

    Path("results").mkdir(exist_ok=True)
    with open("results/typed_gen.json", "w") as f:
        json.dump({"wall_time_s": round(wall_time, 1), "results": clean}, f, indent=2)
    print(f"\nSaved to results/typed_gen.json")
